### PR TITLE
Fix grammar and markdown mistakes in README.md

### PR DESCRIPTION
**Pull request by tiankaima**

### CODE REVIEW

**Comment by chongWjing** [comment]
when 3.1 can update😭

**Comment by JiangGuoo** [comment]
when 3.1 can update😭

**Comment by tiankaima** [comment]
> when 3.1 can update😭

I'm not a maintainer of this project and further work is required for it to work on 3.1
I don't know who u r (not that I care), but plz keep the pr clean.
Try discuss it in discord... stay away from GitHub, plz. Use emojis whenever u can to shorten the conversation.

**Comment by SuMapel** [comment]
So will 3.1 be updated?

**Comment by tiankaima** [comment]
**Again, such comments should be made in discord, which u can find at the homepage**

On that subject though, the author seems to be streaming earlier today... Don't give him too much pressure,

I myself built the project earlier today and there's a lot to work on, give it some time plz, fellow gamers, and try to enjoy the game as mihoyo intended, and have a life, dude.

I don't want any further discussion about that subject though, keep it clean u guys, **READ THE COMMUNITY GUIDELINES BELOW**.

**Review by Hyynn — APPROVED** [review]

**Comment by Taiga74164** [comment]
haha thank you, although i think i'll just keep posting release for this repo to prevent another DMCA take down

**Pull request merged**
